# -*- coding: utf-8 -*-
"""dictionay

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5o0pjxgpIb1h_r38j_Am5vJeut7vYFC
"""

dict1={'a':1,'b':2}
print(dict1)
print(dict1['a'])

dict1={'a':1,'b':2}
print(dict1.keys())

dict1={'a':1,'b':2}
print(dict1.values())

dict1={'a':1,'b':2}
if('a' in dict1.keys()):
  print("Exists")
else:
  print("Not Exists")

n = int(input("Enter the no of pairs :"))
dict1={}
print("Enter the pair values :")
for i in range(n):
  key,val = map(str,input().split())
  dict1[key] = int(val)
print(dict1)

n = int(input("Enter the no of pairs :"))
dict1={}
print("Enter the pair values :")
for i in range(n):
  key,val = map(str,input().split())
  dict1[key] = int(val)
print(dict1)

dict1 = {'c':3,'b':2,'a':1}
print(sorted(dict1.items))

dict1 = {'c':3,'b':2,'a':1}
print(dict(sorted(dict1.items())))

dict1 = {'c':3,'b':2,'a':1}
print(dict(sorted(dict1.items(),reverse = True)))

dict1 = {'c':3,'b':2,'a':1}
ans = dict(sorted(dict1.items(),key = lambda x:x[1]))
print(ans)

#word frequency counter:
#1
s = list(input().split())
dict1 = {}
for i in s:
  if(i in dict1.keys()):
    dict1[i]+=1
  else:
    dict1[i]=1
print(dict1)

#2
s = list(input().split())
dict1 = {}
for i in s:
  dict1[i] = dict1.get(i,0)+1
print(dict1)

s = list(input().split())
dict1 = {}
for i in s:
  dict1[i] = dict1.get(i,0)+1
print(dict1)

n = int(input())
d = {}
for i in range(n):
    name, mark = input().split()
    d[name] = mark
q = input()
if q in d:
    print(d[q])
else:
    print("Not Found")

